version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"
    networks:
      - tr-network
  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"
    networks:
      - tr-network

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "3003:3000"
    networks:
      - tr-network
      
networks:
  tr-network:
    external: true
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./logs:/var/log/nginx
  #   depends_on:
  #     - app1
  #     - app2
  #     - app3