version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - ./nginx-certs/nginx.selfsigned.key:/etc/nginx/certs/nginx.selfsigned.key
      - ./nginx-certs/nginx-selfsigned.crt:/etc/nginx/certs/nginx-selfsigned.crt
    networks:
      - tr-network
# depends_on:
#   - app1
#   - app2
#   - app3

networks:
  tr-network:
    external: true