apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  selector:
    app: nodejs-app
  ports:
  - protocol: TCP
    port: 80         # Port exposed by the service
    targetPort: 3000 # Port on the container/pod to forward traffic to
  type: ClusterIP    # Optional, default is ClusterIP