
all:
  children:
    ubuntu_servers:
      hosts:
        ubuntu-vm:
          ansible_host: 172.22.1.7  # Replace with your Ubuntu VM IP
          ansible_user: azureuser
    redhat_servers:
      hosts:
        redhat-vm:
          ansible_host: 172.22.1.8  # Replace with your RedHat VM IP
          ansible_user: azureuser