apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      terminationGracePeriodSeconds: 100
      containers:
      - name: nodejs-app
        image: nodejs-app
        imagePullPolicy: Never #remove it for azure
        ports:
        - name: http
          containerPort: 3000
        - name: https
          containerPort: 443
        env:
        - name: APP_NAME
          value: "NodeAppReplica"       
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"          
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true